document.write('Navigation');
document.write('<ul class="nav-list">');
document.write('  <li><a href="index.html">Home</a></li>');
document.write('  <li>');
document.write('    <input class="menu-group-input" type="checkbox" name ="topics" id="topics">');
document.write('    <label for="topics">Topics +</label>');
document.write('    <ul class="menu-group-list nav-list">');
document.write('      <li>');
document.write('        <input class="menu-group-input" type="checkbox" name ="class_activities" id="class_activities">');
document.write('        <label for="class_activities">Class Activities +</label>');
document.write('        <ul class="menu-group-list nav-list">');
document.write('          <li><a href="#0">Empty</a></li>');
document.write('        </ul>');
document.write('      </li>');
document.write('      <li><a href="pages_setup_resources.html">Setup Resources</a></li>');
document.write('      <li><a href="pages_html_resources.html">HTML Resources</a></li>');
document.write('    </ul>');
document.write('  </li>');
document.write('  <li><a href="#0">About (Empty)</a></li>');
document.write('</ul>');